package part3.etrading;

import java.lang.management.ManagementFactory;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.BooleanSupplier;

/**
 * PART 3 of SPEC-part3.md in executable form: two checks, both about allocation.
 *
 * <p>This class deliberately has <b>no test-framework dependency</b>, so part 3
 * can be run with nothing but a JDK -- no Gradle, no network, no JUnit:
 *
 * <pre>
 *   ./gradlew part3     run this class directly (no dependencies at all)
 *   ./gradlew test      run the same checks through JUnit, red/green per rule
 * </pre>
 *
 * <p>{@code Part3Tests} in the same package is a thin JUnit wrapper around
 * exactly these methods, so both routes assert the same thing.
 *
 * <p>PLEASE DO NOT EDIT THIS FILE. It is the spec. If you think a check is
 * wrong, say so -- SPEC-part3.md is the arbiter.
 *
 * <p>Both checks share one measurement, run once and cached. Allocation is
 * attributed to the feeding thread plus every thread the aggregator creates, and
 * to nothing else, so the figure is unaffected by whatever else the JVM is doing
 * -- Gradle's test worker, an IDE, JIT threads. That is what makes it safe to run
 * anywhere. The measurement also fails if quotes were dropped or nothing was
 * published: allocating little by throwing work away does not count.
 *
 * <p>This file shares no code with parts 1 and 2, on purpose: the three parts are
 * independent and either can be handed out on its own.
 */
public final class Part3Checks {

    private static final long T0 = 1_000_000_000L;

    private static final long SECOND = 1_000_000_000L;

    private static final int WARMUP_QUOTES = 50_000;

    private static final int MEASURED_QUOTES = 200_000;

    // ---- anything the aggregator's own threads throw, recorded globally -----

    private static final AtomicInteger UNCAUGHT = new AtomicInteger();

    private static volatile Throwable lastUncaught;

    static {
        final Thread.UncaughtExceptionHandler previous =
                Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler((thread, error) -> {
            lastUncaught = error;
            UNCAUGHT.incrementAndGet();
            if (previous != null) {
                previous.uncaughtException(thread, error);
            }
        });
    }

    // ---- the measurement, run once and shared by both rules -----------------

    private static boolean allocMeasured;
    private static double bytesPerQuote;
    private static double producerBytesPerQuote;
    private static double aggregatorBytesPerQuote;
    private static AssertionError allocFailure;

    private Part3Checks() {
    }

    // ============================================================== the rules

    /** Rule 1: under 40 bytes per quote. */
    public static void hotPathAllocatesUnder40BytesPerQuote() throws Exception {
        guard(120_000, () -> {
            double perQuote = measureAllocation();
            if (perQuote >= 40.0) {
                throw new AssertionError(allocationMessage(perQuote, 40));
            }
        });
    }

    /** Rule 2: under 16 bytes per quote. */
    public static void hotPathAllocatesAlmostNothing() throws Exception {
        guard(120_000, () -> {
            double perQuote = measureAllocation();
            if (perQuote >= 16.0) {
                throw new AssertionError(allocationMessage(perQuote, 16));
            }
        });
    }

    // ============================================================= measurement

    private static String allocationMessage(double perQuote, int limit) {
        return String.format(
                "the hot path allocated %.1f bytes per quote over %d quotes; the limit is "
                        + "%d. Split by thread: the feeding thread allocated %.1f bytes per "
                        + "quote, the aggregator's own threads %.1f. Every one of those "
                        + "bytes has to be collected again, and that is where the pauses "
                        + "come from.",
                perQuote, MEASURED_QUOTES, limit, producerBytesPerQuote,
                aggregatorBytesPerQuote);
    }

    /**
     * Runs the load once and caches the result, so the two rules cost one
     * measurement rather than two.
     */
    static synchronized double measureAllocation() throws Exception {
        if (allocMeasured) {
            if (allocFailure != null) {
                throw allocFailure;
            }
            return bytesPerQuote;
        }
        allocMeasured = true;

        Set<Long> preExisting = new HashSet<>();
        for (long id : ManagementFactory.getThreadMXBean().getAllThreadIds()) {
            preExisting.add(id);
        }

        int uncaughtBefore = UNCAUGHT.get();
        PriceAggregatorApi agg = newAggregator();
        Counter published = new Counter();
        agg.addListener(published);
        agg.start();
        try {
            feed(agg, 0, WARMUP_QUOTES, T0);
            awaitTrue(() -> agg.getQuotesProcessed() >= WARMUP_QUOTES, 15_000);
            Thread.sleep(500L);

            long self = Thread.currentThread().getId();
            long feederBefore = allocatedBytes(new long[]{self});
            long othersBefore = allocatedBytes(othersOwned(preExisting, self));

            feed(agg, WARMUP_QUOTES, MEASURED_QUOTES, T0 + 10 * SECOND);
            boolean drained = awaitTrue(
                    () -> agg.getQuotesProcessed() >= WARMUP_QUOTES + MEASURED_QUOTES,
                    30_000);
            Thread.sleep(500L);

            long feederAfter = allocatedBytes(new long[]{self});
            long othersAfter = allocatedBytes(othersOwned(preExisting, self));

            producerBytesPerQuote = (double) (feederAfter - feederBefore) / MEASURED_QUOTES;
            aggregatorBytesPerQuote = (double) (othersAfter - othersBefore) / MEASURED_QUOTES;
            bytesPerQuote = producerBytesPerQuote + aggregatorBytesPerQuote;

            if (UNCAUGHT.get() != uncaughtBefore) {
                allocFailure = new AssertionError(
                        "the aggregator's worker thread died during the load: "
                                + describe(lastUncaught));
            } else if (!drained) {
                allocFailure = new AssertionError(String.format(
                        "%d quotes were offered but only %d reached processing -- %d were "
                                + "dropped. Allocating less by discarding quotes does not "
                                + "count.",
                        WARMUP_QUOTES + MEASURED_QUOTES, agg.getQuotesProcessed(),
                        WARMUP_QUOTES + MEASURED_QUOTES - agg.getQuotesProcessed()));
            } else if (published.count() == 0) {
                allocFailure = new AssertionError(
                        "nothing was published in " + MEASURED_QUOTES + " quotes, so the "
                                + "publish path was never exercised and the allocation "
                                + "figure means nothing");
            }
            if (allocFailure != null) {
                throw allocFailure;
            }
            return bytesPerQuote;
        } finally {
            agg.stop();
        }
    }

    /** Threads that did not exist before the aggregator did, excluding this one. */
    private static long[] othersOwned(Set<Long> preExisting, long self) {
        long[] all = ManagementFactory.getThreadMXBean().getAllThreadIds();
        long[] owned = new long[all.length];
        int n = 0;
        for (long id : all) {
            if (id != self && !preExisting.contains(id)) {
                owned[n++] = id;
            }
        }
        long[] result = new long[n];
        System.arraycopy(owned, 0, result, 0, n);
        return result;
    }

    /** Allocation-free feed loop, so we measure the aggregator and not the check. */
    private static void feed(PriceAggregatorApi agg, long from, int count, long baseTs) {
        for (int i = 0; i < count; i++) {
            SyntheticFeed.send(agg, from + i, baseTs + i * 1_000L);
        }
    }

    private static long allocatedBytes(long[] ids) {
        java.lang.management.ThreadMXBean base = ManagementFactory.getThreadMXBean();
        if (!(base instanceof com.sun.management.ThreadMXBean) || ids.length == 0) {
            return 0L;
        }
        com.sun.management.ThreadMXBean bean = (com.sun.management.ThreadMXBean) base;
        long total = 0L;
        for (long b : bean.getThreadAllocatedBytes(ids)) {
            if (b > 0) {
                total += b;
            }
        }
        return total;
    }

    // ================================================================= support

    static PriceAggregatorApi newAggregator() {
        return new PriceAggregator();
    }

    private interface Body {
        void run() throws Exception;
    }

    /**
     * Runs one check on a daemon thread and gives up after {@code timeoutMs}, so
     * a blocking call fails the check instead of hanging the whole run with no
     * output at all.
     */
    private static void guard(long timeoutMs, Body body) throws Exception {
        final Throwable[] thrown = new Throwable[1];
        Thread t = new Thread(() -> {
            try {
                body.run();
            } catch (Throwable x) {
                thrown[0] = x;
            }
        }, "part3-check");
        t.setDaemon(true);
        t.start();
        t.join(timeoutMs);
        if (t.isAlive()) {
            throw new AssertionError("the check did not return within " + (timeoutMs / 1000)
                    + "s, so something blocked. The usual causes are a producer waiting for "
                    + "room that the worker never frees, or stop() waiting on the worker "
                    + "thread without interrupting it.");
        }
        if (thrown[0] instanceof AssertionError) {
            throw (AssertionError) thrown[0];
        }
        if (thrown[0] instanceof RuntimeException) {
            throw (RuntimeException) thrown[0];
        }
        if (thrown[0] != null) {
            throw new Exception(thrown[0]);
        }
    }

    static boolean awaitTrue(BooleanSupplier condition, long timeoutMs) {
        long deadline = System.currentTimeMillis() + timeoutMs;
        while (System.currentTimeMillis() < deadline) {
            if (condition.getAsBoolean()) {
                return true;
            }
            try {
                Thread.sleep(2L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return false;
            }
        }
        return condition.getAsBoolean();
    }

    private static String describe(Throwable t) {
        if (t == null) {
            return "(unknown)";
        }
        StackTraceElement[] trace = t.getStackTrace();
        String where = trace.length > 0 ? " at " + trace[0] : "";
        return t + where;
    }

    /**
     * Counts callbacks, and allocates nothing itself, so the listener cannot
     * contribute to the figure being measured.
     */
    static final class Counter implements QuoteListener {
        private final AtomicInteger n = new AtomicInteger();

        @Override
        public void onBest(String symbol, double bestBid, double bestAsk, long ts) {
            n.incrementAndGet();
        }

        int count() {
            return n.get();
        }
    }

    // ============================================== standalone runner (no deps)

    private static final class Rule {
        final String title;
        final Body body;

        Rule(String title, Body body) {
            this.title = title;
            this.body = body;
        }
    }

    public static void main(String[] args) {
        List<Rule> rules = new ArrayList<>();
        rules.add(new Rule("1. hot path allocates under 40 bytes per quote",
                Part3Checks::hotPathAllocatesUnder40BytesPerQuote));
        rules.add(new Rule("2. hot path allocates almost nothing (under 16 bytes/quote)",
                Part3Checks::hotPathAllocatesAlmostNothing));

        System.out.println("PART 3 -- checking part3.etrading.PriceAggregator against SPEC-part3.md");
        System.out.println("(running a 250,000 quote load; the report is printed at the end)");
        System.out.println();

        List<String> report = new ArrayList<>();
        int passed = 0;
        for (Rule rule : rules) {
            try {
                rule.body.run();
                report.add("[PASS] " + rule.title);
                passed++;
            } catch (AssertionError err) {
                report.add("[FAIL] " + rule.title);
                report.add("       " + err.getMessage());
            } catch (Exception ex) {
                report.add("[FAIL] " + rule.title);
                report.add("       threw "
                        + describe(ex.getCause() == null ? ex : ex.getCause()));
            }
        }

        System.out.flush();
        try {
            Thread.sleep(150L);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        String bar = "----------------------------------------------------------------";
        StringBuilder out = new StringBuilder();
        out.append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        out.append("PART 3 REPORT -- allocation (part3.etrading.PriceAggregator)")
                .append(System.lineSeparator());
        out.append("(any stack traces above came from the aggregator's own threads)")
                .append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        for (String line : report) {
            out.append(line).append(System.lineSeparator());
        }
        out.append(bar).append(System.lineSeparator());
        out.append(String.format("PART 3   %d / %d passed%n", passed, rules.size()));
        out.append(bar).append(System.lineSeparator());
        if (passed < rules.size()) {
            out.append("Part 3 rules are still violated. SPEC-part3.md says what each "
                    + "rule requires.");
        } else {
            out.append("All part 3 rules satisfied.");
        }
        System.out.println(out);
        System.exit(passed == rules.size() ? 0 : 1);
    }
}
