package part1.fuel;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * PART 1 of SPEC-part1.md in executable form: one check per rule, four rules.
 *
 * <p>This class deliberately has <b>no test-framework dependency</b>, so part 1
 * can be run with nothing but a JDK -- no Gradle, no network, no JUnit:
 *
 * <pre>
 *   ./gradlew part1     run this class directly (no dependencies at all)
 *   ./gradlew test      run the same checks through JUnit, red/green per rule
 * </pre>
 *
 * <p>{@code Part1Tests} in the same package is a thin JUnit wrapper around
 * exactly these methods, so both routes assert the same thing.
 *
 * <p>PLEASE DO NOT EDIT THIS FILE. It is the spec. If you think a check is
 * wrong, say so -- SPEC-part1.md is the arbiter.
 *
 * <p>Part 1 is single-threaded: every timestamp is supplied by the check itself,
 * so nothing here depends on the wall clock or on how fast the machine is, and a
 * getter is read immediately after the {@code onReport} that should have updated
 * it. Each check still runs under a watchdog, so an implementation that blocks
 * fails the check instead of hanging the run with no output, and anything thrown
 * on a thread the board created is reported rather than lost.
 *
 * <p>This file shares no code with parts 2 and 3, on purpose: the three parts are
 * independent and either can be handed out on its own.
 */
public final class Part1Checks {

    private static final double EPS = 1e-9;

    private static final String AREA = "Camden";

    private static final String AREA2 = "Hackney";

    /** Event time, epoch millis. An arbitrary fixed instant: 2024-01-01T00:00:00Z. */
    private static final long T0 = 1_704_067_200_000L;

    private static final long SECOND = 1_000L;

    private static final long MINUTE = 60_000L;

    // ---- anything a thread the board creates throws, recorded globally -------

    private static final AtomicInteger UNCAUGHT = new AtomicInteger();

    private static volatile Throwable lastUncaught;

    static {
        final Thread.UncaughtExceptionHandler previous =
                Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler((thread, error) -> {
            lastUncaught = error;
            UNCAUGHT.incrementAndGet();
            if (previous != null) {
                previous.uncaughtException(thread, error);
            }
        });
    }

    private Part1Checks() {
    }

    // ============================================================== the rules

    /** Rule 1: the published cheapest of each is correct. */
    public static void publishedCheapestIsCorrect() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.report(AREA, "Shell", 1.459, 1.539, T0);
                f.assertPublishes(1, "after Shell's first report for " + AREA
                        + " (the cheapest went from nothing to 1.459 / 1.539)");
                f.assertPublished(AREA, 1.459, 1.539,
                        "the pair delivered after Shell reported 1.459 petrol / 1.539 "
                                + "diesel");
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after Shell reported 1.459 / 1.539");
                assertPrice(1.539, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel after Shell reported 1.459 / 1.539");

                // BP is dearer on petrol but cheaper on diesel. The cheapest petrol
                // must still come from Shell and the cheapest diesel from BP, so the
                // pair is 1.459 / 1.499 and comes from two different stations.
                f.report(AREA, "BP", 1.479, 1.499, T0);
                f.assertPublished(AREA, 1.459, 1.499,
                        "the pair delivered after BP reported 1.479 petrol / 1.499 "
                                + "diesel. Shell is cheapest on petrol (1.459) and BP is "
                                + "cheapest on diesel (1.499), so the two halves of the "
                                + "published pair come from different stations and must be "
                                + "computed independently of one another");
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after BP reported 1.479 / 1.499 (Shell is still "
                                + "cheaper on petrol at 1.459)");
                assertPrice(1.499, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel after BP reported 1.479 / 1.499 (BP is the "
                                + "cheapest on diesel at 1.499 even though Shell is the "
                                + "cheapest on petrol; the cheapest diesel is scanned "
                                + "independently of the petrol price, not read off the "
                                + "cheapest-petrol station's report)");
                f.assertPublishes(2, "after BP's first report (the cheapest diesel "
                        + "improved from 1.539 to 1.499, so the pair moved)");

                // A report for another area must not disturb this one.
                f.report(AREA2, "Shell", 1.429, 1.509, T0);
                f.assertPublished(AREA2, 1.429, 1.509, "the update for " + AREA2);
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol for " + AREA + " after a report for " + AREA2
                                + " (state is per area: one area's reports never affect "
                                + "another's)");
                assertPrice(1.499, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel for " + AREA + " after a report for " + AREA2
                                + " (state is per area: one area's reports never affect "
                                + "another's)");
                f.assertPublishes(3, "after three reports that each moved the cheapest of "
                        + "their own area");
            }
        });
    }

    /** Rule 2: out-of-order reports are ignored. */
    public static void outOfOrderReportsAreIgnored() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.report(AREA, "Shell", 1.459, 1.539, T0);
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after Shell reported 1.459 / 1.539");
                assertCount(1, f.board.getReportsAccepted(),
                        "getReportsAccepted() after one report");

                // Shell re-sends prices stamped five minutes before its own last
                // report: a replayed or delayed webhook. It must not overwrite newer
                // data for that station.
                f.report(AREA, "Shell", 1.699, 1.799, T0 - 5 * MINUTE);
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after Shell sent 1.699 / 1.799 stamped five "
                                + "minutes BEFORE its own last accepted report. A report "
                                + "older than the newest already accepted from that same "
                                + "(area, station) must be discarded, not applied");
                assertPrice(1.539, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel after Shell's out-of-order 1.699 / 1.799 report "
                                + "(it must be discarded, leaving 1.459 / 1.539)");
                assertCount(1, f.board.getReportsAccepted(),
                        "getReportsAccepted() after one accepted report and one discarded "
                                + "out-of-order report (a discarded report is not accepted)");

                // BP's first ever report, stamped 30 seconds before Shell's latest. It
                // is not out of order: the comparison is per (area, station), so
                // Shell's clock says nothing about BP's. 30 s is deep inside the
                // 60-minute TTL of rule 3, so this row is about ordering and nothing
                // else.
                f.report(AREA, "BP", 1.439, 1.549, T0 - 30 * SECOND);
                assertPrice(1.439, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after BP's first report (1.439 / 1.549), which "
                                + "is stamped 30 s earlier than Shell's latest but is BP's "
                                + "own newest -- and still deep inside the 60-minute TTL. "
                                + "Out-of-order is judged per (area, station), never per "
                                + "area");
                assertCount(2, f.board.getReportsAccepted(),
                        "getReportsAccepted() after two accepted reports and one discarded "
                                + "out-of-order report");
            }
        });
    }

    /** Rule 3: stale reports expire. */
    public static void staleReportsExpire() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.report(AREA, "Shell", 1.459, 1.539, T0);
                f.report(AREA, "BP", 1.479, 1.549, T0);
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol while both stations are live");
                assertPrice(1.539, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel while both stations are live");

                // 90 minutes of event time later only BP is still reporting. Shell's
                // last report is now older than the 60-minute TTL measured against the
                // newest timestamp for the area, so it must drop out of BOTH sides
                // until it reports again.
                f.report(AREA, "BP", 1.479, 1.549, T0 + 90 * MINUTE);
                assertPrice(1.479, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol 90 minutes after Shell's last report. Shell "
                                + "reported at T0 and the latest report for " + AREA + " is "
                                + "now T0 + 90 min, so Shell is more than 60 minutes stale "
                                + "and only BP's 1.479 / 1.549 is live. Ages are measured "
                                + "between report timestamps, not against the wall clock");
                assertPrice(1.549, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel 90 minutes of event time after Shell's last "
                                + "report (Shell has expired, so the cheapest live diesel is "
                                + "BP's 1.549, not Shell's 1.539)");

                // It reports again and is live again, on both sides.
                f.report(AREA, "Shell", 1.459, 1.539, T0 + 90 * MINUTE);
                assertPrice(1.459, f.board.getCheapestPetrol(AREA),
                        "getCheapestPetrol after Shell reported again at T0 + 90 min (an "
                                + "expired station comes back as soon as it reports)");
                assertPrice(1.539, f.board.getCheapestDiesel(AREA),
                        "getCheapestDiesel after Shell reported again at T0 + 90 min (an "
                                + "expired station comes back as soon as it reports)");
            }
        });
    }

    /** Rule 4: an update is published exactly when the cheapest changes. */
    public static void publishesExactlyWhenCheapestChanges() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.report(AREA, "Shell", 1.459, 1.539, T0);
                f.assertPublishes(1, "after the first report for " + AREA
                        + " (the cheapest went from nothing to 1.459 / 1.539)");

                // The diesel price drops, the petrol price does not move. The cheapest
                // pair has changed, so exactly one update must go out carrying it.
                f.report(AREA, "Shell", 1.459, 1.519, T0 + MINUTE);
                f.assertPublishes(2, "after Shell cut its diesel price from 1.539 to 1.519 "
                        + "with the petrol price unchanged. A move on EITHER side is a "
                        + "change to the cheapest and publishes exactly one update");
                f.assertPublished(AREA, 1.459, 1.519,
                        "the pair delivered after the diesel price dropped to 1.519");

                // Same petrol, same diesel, newer timestamp: the cheapest has not moved.
                f.report(AREA, "Shell", 1.459, 1.519, T0 + 2 * MINUTE);
                f.assertPublishes(2, "after a report repeating the same 1.459 / 1.519 with "
                        + "a newer timestamp. The cheapest did not move, so nothing may be "
                        + "published -- publishing on every accepted report is wrong");
                assertCount(3, f.board.getReportsAccepted(),
                        "getReportsAccepted() after three reports, all of them in order");
                assertCount(2, f.board.getUpdatesPublished(),
                        "getUpdatesPublished() after three reports that moved the cheapest "
                                + "twice. It must agree with the number of callbacks the "
                                + "listener actually received (" + f.publishes() + ")");
            }
        });
    }

    // ================================================================= support

    private interface Body {
        void run() throws Exception;
    }

    /**
     * Runs one check on a daemon thread and gives up after {@code timeoutMs}, so
     * a blocking or looping implementation fails the check instead of hanging the
     * whole run with no output at all.
     */
    private static void guard(long timeoutMs, Body body) throws Exception {
        final Throwable[] thrown = new Throwable[1];
        Thread t = new Thread(() -> {
            try {
                body.run();
            } catch (Throwable x) {
                thrown[0] = x;
            }
        }, "part1-check");
        t.setDaemon(true);
        t.start();
        t.join(timeoutMs);
        if (t.isAlive()) {
            throw new AssertionError("the check did not return within " + (timeoutMs / 1000)
                    + "s, so something blocked or looped for ever. Part 1 is "
                    + "single-threaded: onReport should do its work on the calling thread "
                    + "and return, and no getter should ever wait for anything.");
        }
        if (thrown[0] instanceof AssertionError) {
            throw (AssertionError) thrown[0];
        }
        if (thrown[0] instanceof RuntimeException) {
            throw (RuntimeException) thrown[0];
        }
        if (thrown[0] != null) {
            throw new Exception(thrown[0]);
        }
    }

    private static void assertPrice(double expected, double actual, String what) {
        if (Double.isNaN(expected) != Double.isNaN(actual)
                || (!Double.isNaN(expected) && Math.abs(expected - actual) > EPS)) {
            throw new AssertionError(String.format(
                    "%s: expected %s but was %s", what, fmtPrice(expected), fmtPrice(actual)));
        }
    }

    private static void assertCount(long expected, long actual, String what) {
        if (expected != actual) {
            throw new AssertionError(String.format(
                    "%s: expected %d but was %d", what, expected, actual));
        }
    }

    private static String fmtPrice(double value) {
        return Double.isNaN(value) ? "NaN" : String.format("%.3f", value);
    }

    private static String describe(Throwable t) {
        if (t == null) {
            return "(unknown)";
        }
        StackTraceElement[] trace = t.getStackTrace();
        String where = trace.length > 0 ? " at " + trace[0] : "";
        return t + where;
    }

    /**
     * One price board plus a listener that records what was actually delivered to
     * it, so a check can assert on the published stream and not only on the
     * getters. A fresh one per rule: nothing carries over.
     */
    static final class Fixture implements AutoCloseable {

        final PriceBoardApi board;

        private final Object lock = new Object();
        private int publishCount;
        private String lastArea;
        private double lastPetrol = Double.NaN;
        private double lastDiesel = Double.NaN;
        private final List<String> recent = new ArrayList<>();

        private final int uncaughtAtStart;

        Fixture() {
            uncaughtAtStart = UNCAUGHT.get();
            board = new PriceBoard();
            board.addListener((area, cheapestPetrol, cheapestDiesel, timestamp) -> {
                synchronized (lock) {
                    publishCount++;
                    lastArea = area;
                    lastPetrol = cheapestPetrol;
                    lastDiesel = cheapestDiesel;
                    if (recent.size() < 12) {
                        recent.add(String.format("%s %s/%s", area, fmtPrice(cheapestPetrol),
                                fmtPrice(cheapestDiesel)));
                    }
                }
            });
        }

        int publishes() {
            synchronized (lock) {
                return publishCount;
            }
        }

        void report(String area, String station, double petrol, double diesel,
                    long timestamp) {
            board.onReport(area, station, petrol, diesel, timestamp);
            assertHealthy();
        }

        /** Fails the check if a thread the board created has died. */
        void assertHealthy() {
            if (UNCAUGHT.get() != uncaughtAtStart) {
                throw new AssertionError("a thread the price board created died with "
                        + describe(lastUncaught) + ". Part 1 is single-threaded: onReport "
                        + "does its work on the calling thread and there is no worker to "
                        + "die.");
            }
        }

        void assertPublishes(int expected, String when) {
            assertHealthy();
            synchronized (lock) {
                if (publishCount != expected) {
                    throw new AssertionError(String.format(
                            "update count %s: expected %d but the listener received %d. "
                                    + "Updates so far: %s",
                            when, expected, publishCount, recentOrNone()));
                }
            }
        }

        void assertPublished(String area, double petrol, double diesel, String what) {
            assertHealthy();
            synchronized (lock) {
                boolean ok = area.equals(lastArea)
                        && Math.abs(petrol - lastPetrol) <= EPS
                        && Math.abs(diesel - lastDiesel) <= EPS;
                if (!ok) {
                    throw new AssertionError(String.format(
                            "%s: expected %s %s petrol / %s diesel but the last update "
                                    + "delivered was %s %s / %s. Updates so far: %s. The "
                                    + "getters currently report %s / %s. The getters and "
                                    + "the published stream must agree.",
                            what, area, fmtPrice(petrol), fmtPrice(diesel),
                            lastArea, fmtPrice(lastPetrol), fmtPrice(lastDiesel),
                            recentOrNone(),
                            fmtPrice(board.getCheapestPetrol(area)),
                            fmtPrice(board.getCheapestDiesel(area))));
                }
            }
        }

        private String recentOrNone() {
            return recent.isEmpty() ? "(none)" : String.join(", ", recent);
        }

        @Override
        public void close() {
            // Nothing to shut down: part 1 owns no threads and no resources.
        }
    }

    // ============================================== standalone runner (no deps)

    private static final class Rule {
        final String title;
        final Body body;

        Rule(String title, Body body) {
            this.title = title;
            this.body = body;
        }
    }

    public static void main(String[] args) {
        List<Rule> rules = new ArrayList<>();
        rules.add(new Rule("1. the published cheapest of each is correct",
                Part1Checks::publishedCheapestIsCorrect));
        rules.add(new Rule("2. out-of-order reports are ignored",
                Part1Checks::outOfOrderReportsAreIgnored));
        rules.add(new Rule("3. stale reports expire",
                Part1Checks::staleReportsExpire));
        rules.add(new Rule("4. an update is published exactly when the cheapest changes",
                Part1Checks::publishesExactlyWhenCheapestChanges));

        System.out.println("PART 1 -- checking part1.fuel.PriceBoard against SPEC-part1.md");
        System.out.println("(running; the report is printed at the end)");
        System.out.println();

        List<String> report = new ArrayList<>();
        int passed = 0;
        for (Rule rule : rules) {
            try {
                rule.body.run();
                report.add("[PASS] " + rule.title);
                passed++;
            } catch (AssertionError err) {
                report.add("[FAIL] " + rule.title);
                report.add("       " + err.getMessage());
            } catch (Exception ex) {
                report.add("[FAIL] " + rule.title);
                report.add("       threw "
                        + describe(ex.getCause() == null ? ex : ex.getCause()));
            }
        }

        System.out.flush();
        try {
            Thread.sleep(150L);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        String bar = "----------------------------------------------------------------";
        StringBuilder out = new StringBuilder();
        out.append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        out.append("PART 1 REPORT -- core functionality (part1.fuel.PriceBoard)")
                .append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        for (String line : report) {
            out.append(line).append(System.lineSeparator());
        }
        out.append(bar).append(System.lineSeparator());
        out.append(String.format("PART 1   %d / %d passed%n", passed, rules.size()));
        out.append(bar).append(System.lineSeparator());
        if (passed < rules.size()) {
            out.append("Part 1 rules are still violated. SPEC-part1.md says what each "
                    + "rule requires.");
        } else {
            out.append("All part 1 rules satisfied.");
        }
        System.out.println(out);
        System.exit(passed == rules.size() ? 0 : 1);
    }
}
