package etrading;

import java.lang.management.ManagementFactory;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.BooleanSupplier;

/**
 * The executable form of SPEC.md: one check per rule.
 *
 * <p>This class deliberately has <b>no test-framework dependency</b> and lives in
 * {@code src/main/java}, so the spec can be run with nothing but a JDK -- no
 * Gradle, no network, no JUnit. {@code SpecTests} in {@code src/test/java} is a
 * thin JUnit wrapper around exactly these methods, so both routes assert the
 * same thing:
 *
 * <pre>
 *   ./gradlew test      run through JUnit (IDE-friendly, red/green per rule)
 *   ./gradlew spec      run this class directly (no dependencies at all)
 * </pre>
 *
 * <p>PLEASE DO NOT EDIT THIS FILE. It is the spec. If you think a check is wrong,
 * say so -- SPEC.md is the arbiter.
 *
 * <p>Behavioural timing is driven by the {@code tsNanos} values supplied by the
 * checks themselves, never by the wall clock, so results do not depend on how
 * fast the machine is. Every check runs under a watchdog and reports if the
 * aggregator's own threads die.
 */
public final class SpecChecks {

    private static final double EPS = 1e-9;

    private static final String SYM = "EURUSD";

    private static final String SYM2 = "USDJPY";

    private static final long T0 = 1_000_000_000L;

    private static final long MILLI = 1_000_000L;

    private static final long SECOND = 1_000_000_000L;

    /** Symbols used by the concurrency check; they come into play progressively. */
    private static final String[] LOAD_SYMBOLS = {
            "EURUSD", "GBPUSD", "USDJPY", "USDCHF",
            "AUDUSD", "USDCAD", "XAUUSD", "XAGUSD"
    };

    // ---- anything the aggregator's own threads throw, recorded globally -----

    private static final AtomicInteger UNCAUGHT = new AtomicInteger();

    private static volatile Throwable lastUncaught;

    static {
        final Thread.UncaughtExceptionHandler previous =
                Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler((thread, error) -> {
            lastUncaught = error;
            UNCAUGHT.incrementAndGet();
            if (previous != null) {
                previous.uncaughtException(thread, error);
            }
        });
    }

    // ---- allocation measurement, run once and shared by rules 5 and 7 ------

    private static boolean allocMeasured;
    private static double bytesPerQuote;
    private static double producerBytesPerQuote;
    private static double aggregatorBytesPerQuote;
    private static AssertionError allocFailure;

    private SpecChecks() {
    }

    // ============================================================== the rules

    /** Rule 1. */
    public static void publishedTopOfBookIsCorrect() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.quote(SYM, "LP-A", 1.10000, 1.10050, T0);
                f.awaitPublishes(1);

                // LP-B outbids LP-A but quotes a worse ask. Best bid must come from
                // LP-B and best ask from LP-A: 1.10020 / 1.10050, not crossed.
                f.quote(SYM, "LP-B", 1.10020, 1.10150, T0);
                f.awaitPublishes(2);

                assertEquals(1.10020, f.agg.getBestBid(SYM), "getBestBid");
                assertEquals(1.10050, f.agg.getBestAsk(SYM),
                        "getBestAsk (LP-A quotes the lower ask 1.10050, LP-B the higher "
                                + "bid 1.10020: the two sides come from different LPs)");
                f.assertPublished(SYM, 1.10020, 1.10050,
                        "the pair delivered to listeners");

                // A quote for another symbol must not disturb this one.
                f.quote(SYM2, "LP-A", 150.100, 150.150, T0);
                f.awaitPublishes(3);
                f.assertPublished(SYM2, 150.100, 150.150, "the update for " + SYM2);
                assertEquals(1.10020, f.agg.getBestBid(SYM),
                        "getBestBid for " + SYM + " after a quote for " + SYM2
                                + " (state is per symbol)");
            }
        });
    }

    /** Rule 2. */
    public static void quotesThatMustNotCountAreExcluded() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.quote(SYM, "LP-A", 1.10000, 1.10050, T0);
                f.awaitBestBid(1.10000);

                // Same LP, older timestamp, worse price: a late or replayed message.
                f.quote(SYM, "LP-A", 1.09000, 1.09050, T0 - SECOND / 2);
                f.settle();
                assertEquals(1.10000, f.agg.getBestBid(SYM),
                        "getBestBid after a late out-of-order quote from the same LP "
                                + "(it must be discarded, not applied)");

                // A different LP's first ever quote, stamped slightly earlier than
                // LP-A's latest. It is not out of order: the comparison is per
                // (symbol, LP), so LP-A's clock says nothing about LP-B's.
                f.quote(SYM, "LP-B", 1.10030, 1.10080, T0 - SECOND / 4);
                f.awaitBestBid(1.10030);
                assertEquals(1.10030, f.agg.getBestBid(SYM),
                        "getBestBid after LP-B's first quote, which is older than LP-A's "
                                + "latest but is LP-B's newest (out-of-order is per "
                                + "(symbol, LP), not per symbol)");
            }

            try (Fixture f = new Fixture()) {
                f.quote(SYM, "LP-A", 1.10000, 1.10050, T0);
                f.quote(SYM, "LP-B", 1.09980, 1.10030, T0);
                f.awaitBestBid(1.10000);

                // Three seconds of event time later only LP-B is still quoting, so
                // LP-A is now beyond the 2s TTL and must drop out of both sides.
                f.quote(SYM, "LP-B", 1.09980, 1.10030, T0 + 3 * SECOND);
                f.awaitBestBid(1.09980);
                assertEquals(1.09980, f.agg.getBestBid(SYM),
                        "getBestBid after LP-A's quote exceeded the 2s TTL");
                assertEquals(1.10030, f.agg.getBestAsk(SYM),
                        "getBestAsk after LP-A's quote exceeded the 2s TTL");
            }
        });
    }

    /** Rule 3. */
    public static void publishesExactlyWhenTopOfBookChanges() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.quote(SYM, "LP-A", 1.10000, 1.10050, T0);
                f.awaitPublishes(1);

                // The ask improves, the bid does not move. Top of book has changed,
                // so exactly one update must go out, carrying the new ask.
                f.quote(SYM, "LP-A", 1.10000, 1.10020, T0 + MILLI);
                f.awaitPublishes(2);
                f.settle();
                assertEquals(2, f.publishes(),
                        "publish count after the ask improved from 1.10050 to 1.10020 "
                                + "with the bid unchanged (an ask-only move is a change)");
                f.assertPublished(SYM, 1.10000, 1.10020,
                        "the pair delivered after the ask improved");

                // Identical prices, newer timestamp: top of book has not moved.
                f.quote(SYM, "LP-A", 1.10000, 1.10020, T0 + 2 * MILLI);
                f.settle();
                assertEquals(2, f.publishes(),
                        "publish count after a quote that does not move top of book "
                                + "(it must produce no callback)");
            }
        });
    }

    /** Rule 4. */
    public static void safeUnderConcurrentProducersAndConsumers() throws Exception {
        guard(45_000, () -> {
            final int producers = 4;
            final int perProducer = 25_000;
            final int total = producers * perProducer;

            try (Fixture f = new Fixture()) {
                if (!f.agg.isRunning()) {
                    throw new AssertionError(
                            "isRunning() is false straight after start() -- the aggregator "
                                    + "must be processing on its own thread");
                }

                // A getter caller on another thread, as the pricing engine is.
                final AtomicLong readerLoops = new AtomicLong();
                final String[] readerFailure = new String[1];
                final boolean[] readerStop = new boolean[1];
                Thread reader = new Thread(() -> {
                    Set<String> seen = new HashSet<>();
                    try {
                        while (!readerStop[0]) {
                            for (String sym : LOAD_SYMBOLS) {
                                double bid = f.agg.getBestBid(sym);
                                double ask = f.agg.getBestAsk(sym);
                                if (!Double.isNaN(bid) && !Double.isNaN(ask)) {
                                    seen.add(sym);
                                } else if (seen.contains(sym) && readerFailure[0] == null) {
                                    readerFailure[0] = sym + " reported a live price and "
                                            + "then reported NaN again (bid " + bid
                                            + ", ask " + ask + "), so the book was seen "
                                            + "half-updated from another thread";
                                }
                            }
                            readerLoops.incrementAndGet();
                        }
                    } catch (Throwable x) {
                        if (readerFailure[0] == null) {
                            readerFailure[0] = "a getter threw " + describe(x)
                                    + ". The book is being mutated while other threads "
                                    + "read it (it survived " + readerLoops.get()
                                    + " clean passes first)";
                        }
                    }
                }, "spec-reader");
                reader.setDaemon(true);
                reader.start();

                List<Thread> feeders = new ArrayList<>();
                for (int p = 0; p < producers; p++) {
                    final String lp = "LP-" + (char) ('A' + p);
                    Thread t = new Thread(() -> {
                        for (int i = 0; i < perProducer; i++) {
                            int symIdx = (int) ((long) i * LOAD_SYMBOLS.length / perProducer);
                            double bid = 1.0 + symIdx * 0.01 + (i % 50) * 0.00001;
                            f.agg.onQuote(LOAD_SYMBOLS[symIdx], lp, bid, bid + 0.001,
                                    T0 + (long) i * 1_000L);
                        }
                    }, "spec-feeder-" + lp);
                    t.setDaemon(true);
                    feeders.add(t);
                    t.start();
                }

                // Listeners arriving while quotes are in flight, as downstream
                // components do when they start up.
                List<Counter> latecomers = new ArrayList<>();
                for (int i = 0; i < 32; i++) {
                    Counter c = new Counter();
                    latecomers.add(c);
                    f.agg.addListener(c);
                    Thread.sleep(2L);
                }

                for (Thread t : feeders) {
                    t.join(20_000L);
                }
                awaitTrue(() -> f.agg.getQuotesProcessed() >= total, 15_000);
                readerStop[0] = true;
                if (readerFailure[0] != null) {
                    throw new AssertionError("a getter caller on another thread saw the "
                            + "book inconsistent: " + readerFailure[0]);
                }
                f.assertHealthy();

                if (f.agg.getQuotesProcessed() != total) {
                    throw new AssertionError(String.format(
                            "%d quotes were offered from %d threads but only %d reached "
                                    + "processing -- %d were lost",
                            total, producers, f.agg.getQuotesProcessed(),
                            total - f.agg.getQuotesProcessed()));
                }
                if (f.publishes() == 0) {
                    throw new AssertionError("nothing was published in " + total
                            + " quotes from " + producers + " threads");
                }

                // A listener registered now must still start receiving updates.
                Counter canary = new Counter();
                f.agg.addListener(canary);
                f.quote("EURGBP", "LP-A", 0.85000, 0.85040, T0 + 60 * SECOND);
                awaitTrue(() -> canary.count() > 0, 2_000);
                f.assertHealthy();
                int latecomerTotal = 0;
                for (Counter c : latecomers) {
                    latecomerTotal += c.count();
                }
                if (latecomerTotal == 0) {
                    throw new AssertionError("32 listeners were registered while quotes "
                            + "were flowing and not one of them ever received an update");
                }
                if (canary.count() == 0) {
                    throw new AssertionError("a listener registered after the feed "
                            + "received no update for a brand new symbol");
                }

                // stop() must return promptly and the worker must actually finish.
                long t0 = System.currentTimeMillis();
                f.agg.stop();
                long stopMs = System.currentTimeMillis() - t0;
                if (stopMs > 250L) {
                    throw new AssertionError("stop() took " + stopMs
                            + " ms to return. It must not block waiting for the worker: "
                            + "signal the worker and return, do not join() it.");
                }
                if (!awaitTrue(() -> !f.agg.isRunning(), 1_000)) {
                    throw new AssertionError(
                            "worker thread still alive one second after stop() returned");
                }
            }
        });
    }

    /** Rule 5. */
    public static void hotPathAllocatesUnder40BytesPerQuote() throws Exception {
        guard(60_000, () -> {
            double perQuote = measureAllocation();
            if (perQuote >= 40.0) {
                throw new AssertionError(allocationMessage(perQuote, 40));
            }
        });
    }

    /** Rule 6 (stretch). */
    public static void crossedBookIsNeverPublished() throws Exception {
        guard(10_000, () -> {
            try (Fixture f = new Fixture()) {
                f.quote(SYM, "LP-A", 1.09900, 1.10050, T0);
                f.awaitPublishes(1);
                int before = f.publishes();

                // LP-B takes the bid above LP-A's ask, so the aggregate is
                // bid 1.10200 / ask 1.10050 -- crossed, and top of book did move.
                f.quote(SYM, "LP-B", 1.10200, 1.10250, T0);
                f.settle();
                if (!f.agg.isCrossed(SYM)) {
                    throw new AssertionError(String.format(
                            "LP-A quotes 1.09900/1.10050 and LP-B quotes 1.10200/1.10250, "
                                    + "so the aggregate is bid 1.10200 / ask 1.10050, which "
                                    + "is crossed. isCrossed() returned false. This "
                                    + "implementation reports bid %.5f / ask %.5f.",
                            f.agg.getBestBid(SYM), f.agg.getBestAsk(SYM)));
                }
                assertEquals(before, f.publishes(),
                        "publish count after the book became crossed (a crossed book must "
                                + "not be published, even though top of book moved)");

                // LP-A withdraws its low ask. The book un-crosses at 1.10200/1.10250
                // and that change must be published.
                f.quote(SYM, "LP-A", 1.09900, 1.10300, T0 + MILLI);
                f.awaitPublishes(before + 1);
                f.settle();
                if (f.agg.isCrossed(SYM)) {
                    throw new AssertionError(String.format(
                            "after LP-A raised its ask to 1.10300 the aggregate is "
                                    + "bid 1.10200 / ask 1.10250 and is no longer crossed, "
                                    + "but isCrossed() still returns true (reported bid "
                                    + "%.5f / ask %.5f)",
                            f.agg.getBestBid(SYM), f.agg.getBestAsk(SYM)));
                }
                assertEquals(before + 1, f.publishes(),
                        "publish count after the book un-crossed (the next genuine change "
                                + "publishes normally)");
                f.assertPublished(SYM, 1.10200, 1.10250,
                        "the pair published once the book un-crossed");
            }
        });
    }

    /** Rule 7 (stretch). */
    public static void hotPathAllocatesAlmostNothing() throws Exception {
        guard(60_000, () -> {
            double perQuote = measureAllocation();
            if (perQuote >= 16.0) {
                throw new AssertionError(allocationMessage(perQuote, 16));
            }
        });
    }

    // ============================================================= measurement

    private static String allocationMessage(double perQuote, int limit) {
        return String.format(
                "hot path allocated %.1f bytes per quote (limit %d) -- feeding thread %.1f, "
                        + "aggregator's own threads %.1f",
                perQuote, limit, producerBytesPerQuote, aggregatorBytesPerQuote);
    }

    /**
     * Runs the load once and caches the result.
     *
     * <p>Allocation is attributed to the feeding thread plus every thread the
     * aggregator creates, and to nothing else -- so the figure is unaffected by
     * whatever else the JVM is doing (Gradle's test worker, the IDE, JIT
     * threads). That is what makes this assertion safe to run anywhere.
     *
     * <p>It also fails if quotes were dropped or nothing was published: allocating
     * little by throwing work away does not count.
     */
    static synchronized double measureAllocation() throws Exception {
        if (allocMeasured) {
            if (allocFailure != null) {
                throw allocFailure;
            }
            return bytesPerQuote;
        }
        allocMeasured = true;
        final int warmup = 50_000;
        final int measured = 200_000;

        Set<Long> preExisting = new HashSet<>();
        for (long id : ManagementFactory.getThreadMXBean().getAllThreadIds()) {
            preExisting.add(id);
        }

        int uncaughtBefore = UNCAUGHT.get();
        PriceAggregatorApi agg = newAggregator();
        Counter published = new Counter();
        agg.addListener(published);
        agg.start();
        try {
            feed(agg, 0, warmup, T0);
            awaitTrue(() -> agg.getQuotesProcessed() >= warmup, 15_000);
            Thread.sleep(500L);

            long self = Thread.currentThread().getId();
            long feederBefore = allocatedBytes(new long[]{self});
            long othersBefore = allocatedBytes(othersOwned(preExisting, self));

            feed(agg, warmup, measured, T0 + 10 * SECOND);
            boolean drained = awaitTrue(
                    () -> agg.getQuotesProcessed() >= warmup + measured, 20_000);
            Thread.sleep(500L);

            long feederAfter = allocatedBytes(new long[]{self});
            long othersAfter = allocatedBytes(othersOwned(preExisting, self));

            producerBytesPerQuote = (double) (feederAfter - feederBefore) / measured;
            aggregatorBytesPerQuote = (double) (othersAfter - othersBefore) / measured;
            bytesPerQuote = producerBytesPerQuote + aggregatorBytesPerQuote;

            if (UNCAUGHT.get() != uncaughtBefore) {
                allocFailure = new AssertionError(
                        "the aggregator's worker thread died during the load: "
                                + describe(lastUncaught));
            } else if (!drained) {
                allocFailure = new AssertionError(String.format(
                        "%d quotes were offered but only %d reached processing -- %d were "
                                + "dropped. Allocating less by discarding quotes does not "
                                + "count.",
                        warmup + measured, agg.getQuotesProcessed(),
                        warmup + measured - agg.getQuotesProcessed()));
            } else if (published.count() == 0) {
                allocFailure = new AssertionError(
                        "nothing was published in " + measured + " quotes, so the publish "
                                + "path was never exercised and the number below means "
                                + "nothing");
            }
            if (allocFailure != null) {
                throw allocFailure;
            }
            return bytesPerQuote;
        } finally {
            agg.stop();
        }
    }

    /** Threads that did not exist before the aggregator did, excluding this one. */
    private static long[] othersOwned(Set<Long> preExisting, long self) {
        long[] all = ManagementFactory.getThreadMXBean().getAllThreadIds();
        long[] owned = new long[all.length];
        int n = 0;
        for (long id : all) {
            if (id != self && !preExisting.contains(id)) {
                owned[n++] = id;
            }
        }
        long[] result = new long[n];
        System.arraycopy(owned, 0, result, 0, n);
        return result;
    }

    /** Allocation-free feed loop, so we measure the aggregator and not the check. */
    private static void feed(PriceAggregatorApi agg, long from, int count, long baseTs) {
        for (int i = 0; i < count; i++) {
            SyntheticFeed.send(agg, from + i, baseTs + i * 1_000L);
        }
    }

    private static long allocatedBytes(long[] ids) {
        java.lang.management.ThreadMXBean base = ManagementFactory.getThreadMXBean();
        if (!(base instanceof com.sun.management.ThreadMXBean) || ids.length == 0) {
            return 0L;
        }
        com.sun.management.ThreadMXBean bean = (com.sun.management.ThreadMXBean) base;
        long total = 0L;
        for (long b : bean.getThreadAllocatedBytes(ids)) {
            if (b > 0) {
                total += b;
            }
        }
        return total;
    }

    // ================================================================= support

    static PriceAggregatorApi newAggregator() {
        return new PriceAggregator();
    }

    private interface Body {
        void run() throws Exception;
    }

    /**
     * Runs one check on a daemon thread and gives up after {@code timeoutMs}, so a
     * blocking call fails the check instead of hanging the whole run with no
     * output at all.
     */
    private static void guard(long timeoutMs, Body body) throws Exception {
        final Throwable[] thrown = new Throwable[1];
        Thread t = new Thread(() -> {
            try {
                body.run();
            } catch (Throwable x) {
                thrown[0] = x;
            }
        }, "spec-check");
        t.setDaemon(true);
        t.start();
        t.join(timeoutMs);
        if (t.isAlive()) {
            throw new AssertionError("the check did not return within " + (timeoutMs / 1000)
                    + "s, so something blocked. The usual cause is stop() waiting on the "
                    + "worker thread without interrupting it, or a getter holding a lock "
                    + "the worker needs.");
        }
        if (thrown[0] instanceof AssertionError) {
            throw (AssertionError) thrown[0];
        }
        if (thrown[0] instanceof RuntimeException) {
            throw (RuntimeException) thrown[0];
        }
        if (thrown[0] != null) {
            throw new Exception(thrown[0]);
        }
    }

    static boolean awaitTrue(BooleanSupplier condition, long timeoutMs) {
        long deadline = System.currentTimeMillis() + timeoutMs;
        while (System.currentTimeMillis() < deadline) {
            if (condition.getAsBoolean()) {
                return true;
            }
            try {
                Thread.sleep(2L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return false;
            }
        }
        return condition.getAsBoolean();
    }

    static void assertEquals(double expected, double actual, String what) {
        if (Double.isNaN(expected) != Double.isNaN(actual)
                || (!Double.isNaN(expected) && Math.abs(expected - actual) > EPS)) {
            throw new AssertionError(String.format(
                    "%s: expected %.5f but was %.5f", what, expected, actual));
        }
    }

    static void assertEquals(int expected, int actual, String what) {
        if (expected != actual) {
            throw new AssertionError(String.format(
                    "%s: expected %d but was %d", what, expected, actual));
        }
    }

    private static String describe(Throwable t) {
        if (t == null) {
            return "(unknown)";
        }
        StackTraceElement[] trace = t.getStackTrace();
        String where = trace.length > 0 ? " at " + trace[0] : "";
        return t + where;
    }

    /** Counts callbacks. Used where only "did anything arrive" matters. */
    static final class Counter implements QuoteListener {
        private final AtomicInteger n = new AtomicInteger();

        @Override
        public void onBest(String symbol, double bestBid, double bestAsk, long ts) {
            n.incrementAndGet();
        }

        int count() {
            return n.get();
        }
    }

    /**
     * One aggregator plus a listener that records what was actually delivered,
     * torn down after each check.
     */
    static final class Fixture implements AutoCloseable {

        final PriceAggregatorApi agg;

        private final Object lock = new Object();
        private int publishCount;
        private String lastSymbol;
        private double lastBid = Double.NaN;
        private double lastAsk = Double.NaN;
        private final List<String> recent = new ArrayList<>();

        private final int uncaughtAtStart;

        Fixture() throws Exception {
            uncaughtAtStart = UNCAUGHT.get();
            agg = newAggregator();
            agg.addListener((symbol, bestBid, bestAsk, ts) -> {
                synchronized (lock) {
                    publishCount++;
                    lastSymbol = symbol;
                    lastBid = bestBid;
                    lastAsk = bestAsk;
                    if (recent.size() < 12) {
                        recent.add(String.format("%s %.5f/%.5f", symbol, bestBid, bestAsk));
                    }
                }
            });
            agg.start();
        }

        int publishes() {
            synchronized (lock) {
                return publishCount;
            }
        }

        void quote(String symbol, String lp, double bid, double ask, long tsNanos) {
            agg.onQuote(symbol, lp, bid, ask, tsNanos);
        }

        /** Fails the check if any thread the aggregator owns has died. */
        void assertHealthy() {
            if (UNCAUGHT.get() != uncaughtAtStart) {
                throw new AssertionError("the aggregator's worker thread died: "
                        + describe(lastUncaught));
            }
        }

        void awaitBestBid(double expected) {
            awaitTrue(() -> Math.abs(agg.getBestBid(SYM) - expected) <= EPS, 2_000);
            assertHealthy();
        }

        void awaitPublishes(int atLeast) {
            awaitTrue(() -> publishes() >= atLeast, 2_000);
            assertHealthy();
        }

        /** Long enough that any update would certainly have been observed. */
        void settle() {
            try {
                Thread.sleep(300L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
            assertHealthy();
        }

        void assertPublished(String symbol, double bid, double ask, String what) {
            assertHealthy();
            synchronized (lock) {
                boolean ok = symbol.equals(lastSymbol)
                        && Math.abs(bid - lastBid) <= EPS
                        && Math.abs(ask - lastAsk) <= EPS;
                if (!ok) {
                    throw new AssertionError(String.format(
                            "%s: expected %s %.5f/%.5f but the last update delivered was "
                                    + "%s %.5f/%.5f. Updates so far: %s. The getters and "
                                    + "the published stream must agree.",
                            what, symbol, bid, ask, lastSymbol, lastBid, lastAsk,
                            recent.isEmpty() ? "(none)" : String.join(", ", recent)));
                }
            }
        }

        @Override
        public void close() {
            agg.stop();
        }
    }

    // ============================================== standalone runner (no deps)

    private static final class Rule {
        final String title;
        final Body body;

        Rule(String title, Body body) {
            this.title = title;
            this.body = body;
        }
    }

    public static void main(String[] args) {
        List<Rule> core = new ArrayList<>();
        core.add(new Rule("1. the published top of book is correct",
                SpecChecks::publishedTopOfBookIsCorrect));
        core.add(new Rule("2. quotes that must not count are excluded",
                SpecChecks::quotesThatMustNotCountAreExcluded));
        core.add(new Rule("3. an update is published exactly when top of book changes",
                SpecChecks::publishesExactlyWhenTopOfBookChanges));
        core.add(new Rule("4. safe under concurrent producers and consumers, and it stops",
                SpecChecks::safeUnderConcurrentProducersAndConsumers));
        core.add(new Rule("5. hot path allocates under 40 bytes per quote",
                SpecChecks::hotPathAllocatesUnder40BytesPerQuote));

        List<Rule> stretch = new ArrayList<>();
        stretch.add(new Rule("6. a crossed book is never published",
                SpecChecks::crossedBookIsNeverPublished));
        stretch.add(new Rule("7. hot path allocates almost nothing (under 16 bytes/quote)",
                SpecChecks::hotPathAllocatesAlmostNothing));

        System.out.println("Checking etrading.PriceAggregator against SPEC.md");
        System.out.println("(running; the report is printed at the end)");
        System.out.println();

        List<String> report = new ArrayList<>();
        int corePassed = runAll(core, report);
        int stretchPassed = runAll(stretch, report);

        System.out.flush();
        try {
            Thread.sleep(150L);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        StringBuilder out = new StringBuilder();
        out.append(System.lineSeparator());
        out.append("----------------------------------------------------------------")
                .append(System.lineSeparator());
        out.append("SPEC REPORT").append(System.lineSeparator());
        out.append("(any stack traces above came from the aggregator's own threads)")
                .append(System.lineSeparator());
        out.append("----------------------------------------------------------------")
                .append(System.lineSeparator());
        for (String line : report) {
            out.append(line).append(System.lineSeparator());
        }
        out.append("----------------------------------------------------------------")
                .append(System.lineSeparator());
        out.append(String.format("CORE     %d / %d passed%n", corePassed, core.size()));
        out.append(String.format("STRETCH  %d / %d passed%n", stretchPassed, stretch.size()));
        out.append("----------------------------------------------------------------")
                .append(System.lineSeparator());
        if (corePassed < core.size()) {
            out.append("Core rules are still violated. SPEC.md says what each rule requires.");
        } else if (stretchPassed < stretch.size()) {
            out.append("All core rules satisfied. Stretch rules remain.");
        } else {
            out.append("All rules satisfied.");
        }
        System.out.println(out);
        System.exit(corePassed == core.size() ? 0 : 1);
    }

    private static int runAll(List<Rule> rules, List<String> report) {
        int passed = 0;
        for (Rule rule : rules) {
            try {
                rule.body.run();
                report.add("[PASS] " + rule.title);
                passed++;
            } catch (AssertionError err) {
                report.add("[FAIL] " + rule.title);
                report.add("       " + err.getMessage());
            } catch (Exception ex) {
                report.add("[FAIL] " + rule.title);
                report.add("       threw " + describe(ex.getCause() == null ? ex : ex.getCause()));
            }
        }
        return passed;
    }
}
