package part2.accounts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.BooleanSupplier;

/**
 * PART 2 of SPEC-part2.md in executable form: one check per rule, five rules.
 *
 * <p>This class deliberately has <b>no test-framework dependency</b>, so part 2
 * can be run with nothing but a JDK -- no Gradle, no network, no JUnit:
 *
 * <pre>
 *   ./gradlew part2     run this class directly (no dependencies at all)
 *   ./gradlew test      run the same checks through JUnit, red/green per rule
 * </pre>
 *
 * <p>{@code Part2Tests} in the same package is a thin JUnit wrapper around
 * exactly these methods, so both routes assert the same thing.
 *
 * <p>PLEASE DO NOT EDIT THIS FILE. It is the spec. If you think a check is
 * wrong, say so -- SPEC-part2.md is the arbiter.
 *
 * <p><b>Every check here is deterministic.</b> None of them depends on winning a
 * race, on JIT behaviour or on luck.
 *
 * <ul>
 *   <li>The contention checks (rules 1, 2 and 4) put two threads on a spin
 *       rendezvous before every single operation, so the two really do enter the
 *       same code within nanoseconds of each other, tens of thousands of times.
 *       A {@code CyclicBarrier} would not do -- it hands the last arrival a head
 *       start over the threads it has to unpark, and that head start is enough to
 *       hide every defect below.</li>
 *   <li>Rule 3 does not race at all: it holds the first thread that constructs an
 *       {@code Account} inside the constructor until a second one has got there,
 *       so an implementation that decides to create outside mutual exclusion is
 *       guaranteed to create twice.</li>
 *   <li>Rule 5 measures wall-clock time against a budget the correct code beats
 *       by two orders of magnitude.</li>
 * </ul>
 *
 * <p>None of it depends on the machine being wide: two cores are enough, and
 * nothing here needs more.
 *
 * <p><b>Part 2 is the diagnosis exercise, so the failure messages are the
 * product.</b> Each one reports what was observed against what was required, and
 * the deadlock check prints a filtered thread dump of the two stuck threads. Read
 * the message; you should not need to read this file.
 *
 * <p>Each check runs under a watchdog on a daemon thread, so a hang is reported
 * as a failure with evidence instead of stopping the run dead. Anything thrown on
 * a thread the service creates is captured and reported too.
 *
 * <p>This file shares no code with parts 1 and 3, on purpose: the three parts are
 * independent and either can be handed out on its own.
 */
public final class Part2Checks {

    /**
     * How many threads the contention checks use. Two, and deliberately two: a
     * lost update or a lost map entry needs the two threads to be inside the same
     * few instructions at the same instant, and two threads is the most that any
     * machine with at least two cores is guaranteed to run at the same instant.
     * Four threads on a two-core box take turns, and a check that only fails when
     * the box is wide enough is not a check.
     */
    private static final int CONTENDING_THREADS = 2;

    // ---- rule 1 -------------------------------------------------------------

    private static final int CREDITS_PER_THREAD = 50_000;

    // ---- rule 2 -------------------------------------------------------------

    private static final int ACCOUNTS_PER_THREAD = 10_000;

    // ---- rule 3 -------------------------------------------------------------

    private static final int RACE_THREADS = 8;

    /**
     * How long the first thread to construct an Account is held inside the
     * constructor, waiting for a second one to arrive. Long enough that the other
     * seven threads have certainly been scheduled; short enough that a correct
     * implementation, where no second thread can ever get there, only pays it
     * once.
     */
    private static final long HOOK_WAIT_MILLIS = 2_000L;

    // ---- rule 4 -------------------------------------------------------------

    private static final int TRANSFERS = 20_000;

    private static final long TRANSFER_BUDGET_MILLIS = 10_000L;

    private static final String A_TO_B = "part2-transfer-A-to-B";

    private static final String B_TO_A = "part2-transfer-B-to-A";

    // ---- rule 5 -------------------------------------------------------------

    private static final long STOP_RETURN_BUDGET_MILLIS = 250L;

    private static final long STOP_FINISH_BUDGET_MILLIS = 1_000L;

    /** How long the service is left running before stop() is called. */
    private static final long SETTLE_MILLIS = 500L;

    // ---- anything a thread the service creates throws, recorded globally ----

    private static final AtomicInteger UNCAUGHT = new AtomicInteger();

    private static volatile Throwable lastUncaught;

    static {
        final Thread.UncaughtExceptionHandler previous =
                Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler((thread, error) -> {
            lastUncaught = error;
            UNCAUGHT.incrementAndGet();
            if (previous != null) {
                previous.uncaughtException(thread, error);
            }
        });
    }

    private Part2Checks() {
    }

    // ============================================================== the rules

    /** Rule 1: no lost updates. */
    public static void creditsAreNotLost() throws Exception {
        guard(60_000, () -> {
            try (Fixture f = new Fixture()) {
                final String id = "ACC-1";
                f.service.getOrCreate(id);

                final long expected = (long) CONTENDING_THREADS * CREDITS_PER_THREAD;
                final AtomicInteger reached = new AtomicInteger();
                Workers workers = new Workers();
                for (int t = 0; t < CONTENDING_THREADS; t++) {
                    workers.start("part2-credit-" + t, () -> {
                        for (int i = 0; i < CREDITS_PER_THREAD; i++) {
                            // Both threads call credit() on the same account within
                            // nanoseconds of each other, 50,000 times over. Nothing
                            // is left to the scheduler's mood.
                            rendezvous(reached, i);
                            f.service.credit(id, 1L);
                        }
                    });
                }
                workers.joinAll(30_000L);
                workers.assertNoneThrew("credit()");
                f.assertServiceThreadsAlive();

                long balance = f.service.getBalance(id);
                if (balance != expected) {
                    throw new AssertionError(String.format(
                            "%d threads each applied credit(\"%s\", 1) %d times, so the "
                                    + "balance must be exactly %d. It was %d -- %d "
                                    + "increments were lost. Both threads read the same "
                                    + "balance, both added one, and one of the two writes "
                                    + "overwrote the other: read-modify-write on a plain "
                                    + "long is three separate steps, not one.",
                            CONTENDING_THREADS, id, CREDITS_PER_THREAD, expected, balance,
                            expected - balance));
                }
                long ops = f.service.getOperationCount();
                if (ops != expected) {
                    throw new AssertionError(String.format(
                            "the balance came out right but getOperationCount() was %d "
                                    + "after %d credit() calls -- %d were lost. The "
                                    + "operation counter is incremented the same "
                                    + "non-atomic way and needs the same fix.",
                            ops, expected, expected - ops));
                }
            }
        });
    }

    /** Rule 2: concurrent account creation does not lose accounts. */
    public static void concurrentCreationDoesNotLoseAccounts() throws Exception {
        guard(60_000, () -> {
            try (Fixture f = new Fixture()) {
                final int expected = CONTENDING_THREADS * ACCOUNTS_PER_THREAD;

                final AtomicInteger reached = new AtomicInteger();
                Workers workers = new Workers();
                for (int t = 0; t < CONTENDING_THREADS; t++) {
                    final int thread = t;
                    workers.start("part2-create-" + t, () -> {
                        for (int i = 0; i < ACCOUNTS_PER_THREAD; i++) {
                            // Both threads create their i-th account at the same
                            // instant, 10,000 times over, so the two put() calls
                            // really do overlap instead of taking turns.
                            rendezvous(reached, i);
                            f.service.getOrCreate(id(thread, i));
                        }
                    });
                }
                boolean finished = workers.joinAll(30_000L);
                if (!finished) {
                    throw new AssertionError(String.format(
                            "%d threads creating %d accounts each did not finish in 30s. "
                                    + "A java.util.HashMap mutated from several threads can "
                                    + "corrupt its own bucket chains, and a lookup that "
                                    + "lands in a corrupted chain never returns.%n%s",
                            CONTENDING_THREADS, ACCOUNTS_PER_THREAD, workers.dump()));
                }
                workers.assertNoneThrew("getOrCreate() during concurrent creation");
                f.assertServiceThreadsAlive();

                int count = f.service.getAccountCount();
                if (count != expected) {
                    throw new AssertionError(String.format(
                            "%d threads created %d distinct accounts each, so "
                                    + "getAccountCount() must be exactly %d. It was %d -- "
                                    + "%d accounts were lost. Concurrent put() into an "
                                    + "unsynchronised HashMap drops entries: both threads "
                                    + "wrote a new node into the same bucket, and the "
                                    + "second write threw the first one away. Resizing "
                                    + "from two threads at once loses whole buckets.",
                            CONTENDING_THREADS, ACCOUNTS_PER_THREAD, expected, count,
                            expected - count));
                }

                List<String> missing = new ArrayList<>();
                for (int t = 0; t < CONTENDING_THREADS && missing.size() < 5; t++) {
                    for (int i = 0; i < ACCOUNTS_PER_THREAD && missing.size() < 5; i++) {
                        String id = id(t, i);
                        Account account = f.service.getOrCreate(id);
                        if (account == null || !id.equals(account.getId())) {
                            missing.add(id + " -> " + account);
                        }
                    }
                }
                if (!missing.isEmpty()) {
                    throw new AssertionError(String.format(
                            "getAccountCount() was right but %d of the created ids do not "
                                    + "come back from getOrCreate(): %s. The map is holding "
                                    + "entries under the wrong keys, which is what "
                                    + "concurrent resizing of a HashMap does.",
                            missing.size(), String.join(", ", missing)));
                }
            }
        });
    }

    /** Rule 3: getOrCreate creates exactly one account per id. */
    public static void getOrCreateCreatesOneAccountPerId() throws Exception {
        guard(60_000, () -> {
            try (Fixture f = new Fixture()) {
                final String id = "RACE-" + System.nanoTime();
                final Account[] handedOut = new Account[RACE_THREADS];

                // Nothing here is left to chance. The first thread that constructs
                // an Account is held inside the constructor until a second thread
                // reaches the same point, or for HOOK_WAIT_MILLIS if no second
                // thread ever does. So an implementation that decides to create
                // outside mutual exclusion is guaranteed to create twice, and one
                // that creates under mutual exclusion is guaranteed to create once
                // -- whatever the machine, the core count and the JIT are doing.
                final CountDownLatch bothInside = new CountDownLatch(2);
                Account.constructionHook = () -> {
                    bothInside.countDown();
                    try {
                        bothInside.await(HOOK_WAIT_MILLIS, TimeUnit.MILLISECONDS);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                    }
                };

                long constructedBefore = Account.constructionCount();
                Workers workers = new Workers();
                try {
                    for (int t = 0; t < RACE_THREADS; t++) {
                        final int slot = t;
                        workers.start("part2-race-" + t,
                                () -> handedOut[slot] = f.service.getOrCreate(id));
                    }
                    workers.joinAll(30_000L);
                } finally {
                    Account.constructionHook = null;
                }
                workers.assertNoneThrew("getOrCreate() while " + RACE_THREADS
                        + " threads raced on a brand new id");
                f.assertServiceThreadsAlive();

                long constructed = Account.constructionCount() - constructedBefore;
                if (constructed != 1L) {
                    throw new AssertionError(String.format(
                            "%d threads called getOrCreate(\"%s\") for an id that did not "
                                    + "exist yet. Exactly one Account must be constructed; "
                                    + "%d were. \"look, then create\" is two operations, and "
                                    + "the first thread had not finished creating when the "
                                    + "others looked, so they all looked, all found nothing, "
                                    + "and all created. getAccountCount() is now %d. Note "
                                    + "that putIfAbsent(id, new Account(id)) does not fix "
                                    + "this: it constructs the account before it knows "
                                    + "whether it is needed, and then throws it away.",
                            RACE_THREADS, id, constructed, f.service.getAccountCount()));
                }

                Account first = handedOut[0];
                int distinct = 0;
                Set<Integer> seen = new HashSet<>();
                for (Account account : handedOut) {
                    if (seen.add(System.identityHashCode(account))) {
                        distinct++;
                    }
                }
                if (distinct != 1) {
                    throw new AssertionError(String.format(
                            "exactly one Account was constructed, but the %d callers were "
                                    + "handed %d different objects back: %s. Every caller "
                                    + "must receive the same instance, or two request "
                                    + "threads will be crediting two different objects for "
                                    + "the same account.",
                            RACE_THREADS, distinct, Arrays.toString(handedOut)));
                }
                if (first == null) {
                    throw new AssertionError(
                            "getOrCreate() returned null while several threads raced on a "
                                    + "new id. It must never return null.");
                }
            }
        });
    }

    /** Rule 4: transfer does not deadlock. */
    public static void transferDoesNotDeadlock() throws Exception {
        guard(60_000, () -> {
            try (Fixture f = new Fixture()) {
                final String a = "ACC-A";
                final String b = "ACC-B";
                f.service.getOrCreate(a);
                f.service.getOrCreate(b);
                f.service.credit(a, TRANSFERS);
                f.service.credit(b, TRANSFERS);

                final AtomicLong doneAtoB = new AtomicLong();
                final AtomicLong doneBtoA = new AtomicLong();
                // The two threads meet on a spin rendezvous before every single
                // transfer: each one announces that it has reached iteration i and
                // then spins until the other has too, so both enter transfer()
                // within nanoseconds of each other, 20,000 times. Both threads are
                // hot on a core throughout -- no parking, no lock, no barrier -- so
                // nothing here quietly serialises them. Argument-order locking gets
                // 20,000 simultaneous attempts and needs to lose only one.
                final AtomicInteger reached = new AtomicInteger();

                Workers workers = new Workers();
                workers.start(A_TO_B, () -> {
                    for (int i = 0; i < TRANSFERS; i++) {
                        rendezvous(reached, i);
                        f.service.transfer(a, b, 1L);
                        doneAtoB.incrementAndGet();
                    }
                });
                workers.start(B_TO_A, () -> {
                    for (int i = 0; i < TRANSFERS; i++) {
                        rendezvous(reached, i);
                        f.service.transfer(b, a, 1L);
                        doneBtoA.incrementAndGet();
                    }
                });

                boolean finished = workers.joinAll(TRANSFER_BUDGET_MILLIS);
                if (!finished) {
                    throw new AssertionError(String.format(
                            "the run did not finish: two threads each hold one of the two "
                                    + "locks and wait for the other.%n"
                                    + "  %s completed %d of %d transfers%n"
                                    + "  %s completed %d of %d transfers%n"
                                    + "  budget was %d ms; neither thread can make progress "
                                    + "again, so waiting longer will not help%n"
                                    + "%s%n%s%n"
                                    + "transfer() takes the two account locks in the order "
                                    + "its arguments happen to arrive in, so A-to-B locks A "
                                    + "then wants B while B-to-A locks B then wants A. The "
                                    + "two directions of the same pair of accounts are "
                                    + "enough.",
                            A_TO_B, doneAtoB.get(), TRANSFERS,
                            B_TO_A, doneBtoA.get(), TRANSFERS,
                            TRANSFER_BUDGET_MILLIS,
                            jvmDeadlockReport(),
                            threadDump(workers.threads())));
                }
                workers.assertNoneThrew("transfer()");
                f.assertServiceThreadsAlive();

                if (doneAtoB.get() != TRANSFERS || doneBtoA.get() != TRANSFERS) {
                    throw new AssertionError(String.format(
                            "both threads returned but only %d of %d and %d of %d transfers "
                                    + "were completed", doneAtoB.get(), TRANSFERS,
                            doneBtoA.get(), TRANSFERS));
                }
            }
        });
    }

    /** Rule 5: stop() returns promptly and the background thread finishes. */
    public static void stopIsPromptAndTheThreadFinishes() throws Exception {
        guard(60_000, () -> {
            try (Fixture f = new Fixture()) {
                if (!f.service.isRunning()) {
                    throw new AssertionError(
                            "isRunning() was false straight after start(). The service must "
                                    + "have its background thread running between start() "
                                    + "and stop().");
                }

                // Let the service settle into steady state before shutting it down,
                // as it would have been for hours before a deploy. Stopping a
                // background thread in the microsecond before it has run its first
                // instruction proves nothing.
                Thread.sleep(SETTLE_MILLIS);
                if (!f.service.isRunning()) {
                    throw new AssertionError(String.format(
                            "isRunning() was false %d ms after start(), before anything "
                                    + "asked it to stop. The background thread must stay "
                                    + "alive until stop() is called.", SETTLE_MILLIS));
                }

                long began = System.nanoTime();
                f.service.stop();
                long returnedInMillis = (System.nanoTime() - began) / 1_000_000L;
                if (returnedInMillis > STOP_RETURN_BUDGET_MILLIS) {
                    throw new AssertionError(String.format(
                            "stop() took %d ms to return; the budget is %d ms. It must "
                                    + "signal the background thread and return, not block "
                                    + "waiting for it.%n%s",
                            returnedInMillis, STOP_RETURN_BUDGET_MILLIS,
                            threadDump(f.serviceThreads())));
                }

                boolean finished = awaitTrue(() -> !f.service.isRunning(),
                        STOP_FINISH_BUDGET_MILLIS);
                if (!finished) {
                    throw new AssertionError(String.format(
                            "stop() returned in %d ms, but isRunning() was still true %d ms "
                                    + "later, so the background thread had not finished. It "
                                    + "is asleep: it waits a fixed interval and only then "
                                    + "looks at the flag again, so shutdown takes as long as "
                                    + "that interval however early stop() is called. A "
                                    + "rolling restart has hundreds of milliseconds, not "
                                    + "tens of seconds. Wait on something that stop() can "
                                    + "wake, or interrupt the thread.%n%s",
                            returnedInMillis, STOP_FINISH_BUDGET_MILLIS,
                            threadDump(f.serviceThreads())));
                }
            }
        });
    }

    // ================================================================= support

    private static String id(int thread, int index) {
        return "T" + thread + "-ACC-" + index;
    }

    /**
     * The {@value #CONTENDING_THREADS} contending threads meeting at iteration
     * {@code i}, without parking either of them.
     * The thread that gets here first spins; the second one's increment releases
     * it, and both are running on a core already, so both leave within
     * nanoseconds of each other. A {@code CyclicBarrier} would not do: it hands
     * the last arrival a head start over the ones it has to unpark, which is
     * exactly the interleaving these checks need to avoid.
     */
    private static void rendezvous(AtomicInteger reached, int iteration) {
        int target = CONTENDING_THREADS * (iteration + 1);
        reached.incrementAndGet();
        while (reached.get() < target) {
            Thread.onSpinWait();
        }
    }

    private interface Body {
        void run() throws Exception;
    }

    /**
     * Runs one check on a daemon thread and gives up after {@code timeoutMs}, so
     * a check that wedges is reported as a failure rather than stopping the run
     * with no output at all. Rules 2 and 4 police their own, shorter budgets and
     * produce better evidence, so this outer watchdog is only the backstop.
     */
    private static void guard(long timeoutMs, Body body) throws Exception {
        final Throwable[] thrown = new Throwable[1];
        Thread t = new Thread(() -> {
            try {
                body.run();
            } catch (Throwable x) {
                thrown[0] = x;
            }
        }, "part2-check");
        t.setDaemon(true);
        t.start();
        t.join(timeoutMs);
        if (t.isAlive()) {
            throw new AssertionError("the check itself did not return within "
                    + (timeoutMs / 1000) + "s, so something blocked that this check does "
                    + "not have a specific message for. " + jvmDeadlockReport());
        }
        if (thrown[0] instanceof AssertionError) {
            throw (AssertionError) thrown[0];
        }
        if (thrown[0] instanceof RuntimeException) {
            throw (RuntimeException) thrown[0];
        }
        if (thrown[0] != null) {
            throw new Exception(thrown[0]);
        }
    }

    static boolean awaitTrue(BooleanSupplier condition, long timeoutMs) {
        long deadline = System.currentTimeMillis() + timeoutMs;
        while (System.currentTimeMillis() < deadline) {
            if (condition.getAsBoolean()) {
                return true;
            }
            try {
                Thread.sleep(2L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return false;
            }
        }
        return condition.getAsBoolean();
    }

    /**
     * A thread dump filtered to the threads that matter, six frames each. The
     * whole point of part 2 is that the message is evidence, so this is here
     * rather than left to the reader.
     */
    private static String threadDump(List<Thread> of) {
        Map<Thread, StackTraceElement[]> all = Thread.getAllStackTraces();
        StringBuilder out = new StringBuilder();
        out.append("thread dump, top 6 frames of each thread involved:");
        for (Thread t : of) {
            StackTraceElement[] frames = all.get(t);
            out.append(System.lineSeparator())
                    .append("  \"").append(t.getName()).append("\" ").append(t.getState());
            if (frames == null || frames.length == 0) {
                out.append(System.lineSeparator()).append("      (no stack available)");
                continue;
            }
            int limit = Math.min(6, frames.length);
            for (int i = 0; i < limit; i++) {
                out.append(System.lineSeparator()).append("      at ").append(frames[i]);
            }
            if (frames.length > limit) {
                out.append(System.lineSeparator())
                        .append("      ... ").append(frames.length - limit).append(" more");
            }
        }
        return out.toString();
    }

    /** What the JVM's own monitor-deadlock detector makes of the situation. */
    private static String jvmDeadlockReport() {
        long[] ids = java.lang.management.ManagementFactory.getThreadMXBean()
                .findMonitorDeadlockedThreads();
        if (ids == null || ids.length == 0) {
            return "  the JVM's own deadlock detector found no monitor deadlock";
        }
        StringBuilder out = new StringBuilder(
                "  the JVM's own deadlock detector reports these threads deadlocked on "
                        + "monitors:");
        for (java.lang.management.ThreadInfo info : java.lang.management.ManagementFactory
                .getThreadMXBean().getThreadInfo(ids)) {
            if (info == null) {
                continue;
            }
            out.append(System.lineSeparator())
                    .append("    \"").append(info.getThreadName()).append("\" is ")
                    .append(info.getThreadState())
                    .append(" waiting to lock ").append(info.getLockName())
                    .append(" which is held by \"").append(info.getLockOwnerName())
                    .append("\"");
        }
        return out.toString();
    }

    private static String describe(Throwable t) {
        if (t == null) {
            return "(unknown)";
        }
        StackTraceElement[] trace = t.getStackTrace();
        String where = trace.length > 0 ? " at " + trace[0] : "";
        return t + where;
    }

    /**
     * A group of load threads, each of which records whatever it throws instead
     * of letting it disappear onto the console. What a thread threw is evidence,
     * so it belongs in the failure message.
     */
    static final class Workers {

        private final List<Thread> threads = new ArrayList<>();
        private final List<Throwable> failures = new ArrayList<>();
        private final List<String> failedIn = new ArrayList<>();

        void start(String name, Body body) {
            Thread t = new Thread(() -> {
                try {
                    body.run();
                } catch (Throwable x) {
                    synchronized (Workers.this) {
                        failures.add(x);
                        failedIn.add(Thread.currentThread().getName());
                    }
                }
            }, name);
            t.setDaemon(true);
            threads.add(t);
            t.start();
        }

        List<Thread> threads() {
            return threads;
        }

        /** True if every thread finished inside the budget. */
        boolean joinAll(long timeoutMillis) throws InterruptedException {
            long deadline = System.currentTimeMillis() + timeoutMillis;
            for (Thread t : threads) {
                long left = deadline - System.currentTimeMillis();
                if (left > 0) {
                    t.join(left);
                }
            }
            for (Thread t : threads) {
                if (t.isAlive()) {
                    return false;
                }
            }
            return true;
        }

        synchronized void assertNoneThrew(String what) {
            if (failures.isEmpty()) {
                return;
            }
            StringBuilder out = new StringBuilder(String.format(
                    "%d of %d load threads died inside %s. That is a data structure being "
                            + "mutated by several threads at once, not a bug in the load:",
                    failures.size(), threads.size(), what));
            for (int i = 0; i < failures.size() && i < 3; i++) {
                out.append(System.lineSeparator())
                        .append("  \"").append(failedIn.get(i)).append("\" threw ")
                        .append(describe(failures.get(i)));
            }
            throw new AssertionError(out.toString());
        }

        String dump() {
            return threadDump(threads);
        }
    }

    /**
     * One account service, started, plus the identity of every thread it created,
     * so a failure message can dump those threads and only those. Stopped after
     * each check.
     */
    static final class Fixture implements AutoCloseable {

        final AccountServiceApi service;

        private final Set<Thread> preExisting;

        private final int uncaughtAtStart;

        Fixture() {
            uncaughtAtStart = UNCAUGHT.get();
            preExisting = new HashSet<>(Thread.getAllStackTraces().keySet());
            service = new AccountService();
            service.start();
        }

        /** Threads that did not exist before this service did. */
        List<Thread> serviceThreads() {
            List<Thread> owned = new ArrayList<>();
            for (Thread t : Thread.getAllStackTraces().keySet()) {
                if (!preExisting.contains(t) && !t.getName().startsWith("part2-")) {
                    owned.add(t);
                }
            }
            return owned;
        }

        /** Fails the check if a thread the service created has died throwing. */
        void assertServiceThreadsAlive() {
            if (UNCAUGHT.get() != uncaughtAtStart) {
                throw new AssertionError("a thread the account service created died with "
                        + describe(lastUncaught)
                        + ". Its background thread must survive concurrent use.");
            }
        }

        @Override
        public void close() {
            service.stop();
        }
    }

    // ============================================== standalone runner (no deps)

    private static final class Rule {
        final String title;
        final Body body;

        Rule(String title, Body body) {
            this.title = title;
            this.body = body;
        }
    }

    public static void main(String[] args) {
        List<Rule> rules = new ArrayList<>();
        rules.add(new Rule("1. no lost updates",
                Part2Checks::creditsAreNotLost));
        rules.add(new Rule("2. concurrent account creation does not lose accounts",
                Part2Checks::concurrentCreationDoesNotLoseAccounts));
        rules.add(new Rule("3. getOrCreate creates exactly one account per id",
                Part2Checks::getOrCreateCreatesOneAccountPerId));
        rules.add(new Rule("4. transfer does not deadlock",
                Part2Checks::transferDoesNotDeadlock));
        rules.add(new Rule("5. stop() returns promptly and the background thread finishes",
                Part2Checks::stopIsPromptAndTheThreadFinishes));

        System.out.println("PART 2 -- checking part2.accounts.AccountService against SPEC-part2.md");
        System.out.println("(running; the report is printed at the end)");
        System.out.println();

        List<String> report = new ArrayList<>();
        int passed = 0;
        for (Rule rule : rules) {
            try {
                rule.body.run();
                report.add("[PASS] " + rule.title);
                passed++;
            } catch (AssertionError err) {
                report.add("[FAIL] " + rule.title);
                for (String line : String.valueOf(err.getMessage()).split("\\R")) {
                    report.add("       " + line);
                }
            } catch (Exception ex) {
                report.add("[FAIL] " + rule.title);
                report.add("       threw "
                        + describe(ex.getCause() == null ? ex : ex.getCause()));
            }
        }

        System.out.flush();
        try {
            Thread.sleep(150L);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        String bar = "----------------------------------------------------------------";
        StringBuilder out = new StringBuilder();
        out.append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        out.append("PART 2 REPORT -- concurrency and diagnosis "
                + "(part2.accounts.AccountService)").append(System.lineSeparator());
        out.append("(any stack traces above came from the service's own threads)")
                .append(System.lineSeparator());
        out.append(bar).append(System.lineSeparator());
        for (String line : report) {
            out.append(line).append(System.lineSeparator());
        }
        out.append(bar).append(System.lineSeparator());
        out.append(String.format("PART 2   %d / %d passed%n", passed, rules.size()));
        out.append(bar).append(System.lineSeparator());
        if (passed < rules.size()) {
            out.append("Part 2 rules are still violated. SPEC-part2.md says what each "
                    + "rule requires.");
        } else {
            out.append("All part 2 rules satisfied.");
        }
        System.out.println(out);
        System.exit(passed == rules.size() ? 0 : 1);
    }
}
